import type { IconType } from 'react-icons';
import {
  IoAdd,
  IoAddCircleOutline,
  IoArrowBack,
  IoArrowForward,
  IoArrowForwardCircle,
  IoBagOutline,
  IoBedOutline,
  IoBicycleOutline,
  IoCalendarOutline,
  IoCall,
  IoCardOutline,
  IoCartOutline,
  IoCashOutline,
  IoCheckmark,
  IoCheckmarkCircle,
  IoChatbubbleOutline,
  IoChatbubblesOutline,
  IoChevronBack,
  IoChevronForward,
  IoClipboardOutline,
  IoClose,
  IoCloseCircle,
  IoConstructOutline,
  IoCopyOutline,
  IoCreateOutline,
  IoCubeOutline,
  IoEllipseOutline,
  IoFlameOutline,
  IoFlashOutline,
  IoGiftOutline,
  IoGridOutline,
  IoHeadsetOutline,
  IoHeart,
  IoHomeOutline,
  IoInformationCircle,
  IoInformationCircleOutline,
  IoLocation,
  IoLocationOutline,
  IoLocationSharp,
  IoLogOutOutline,
  IoLogoWhatsapp,
  IoMapOutline,
  IoMegaphoneOutline,
  IoNavigate,
  IoPaperPlaneOutline,
  IoPowerOutline,
  IoPeopleOutline,
  IoPersonOutline,
  IoRemoveCircleOutline,
  IoRestaurantOutline,
  IoRibbonOutline,
  IoShieldCheckmark,
  IoSparklesOutline,
  IoStar,
  IoStarOutline,
  IoSyncOutline,
  IoLayersOutline,
  IoLocateOutline,
  IoNavigateOutline,
  IoSearchOutline,
  IoShieldOutline,
  IoTrashOutline,
  IoWalletOutline,
  IoWaterOutline,
} from 'react-icons/io5';

const byIon: Record<string, IconType> = {
  'home-outline': IoHomeOutline,
  'bed-outline': IoBedOutline,
  'water-outline': IoWaterOutline,
  'flame-outline': IoFlameOutline,
  'sparkles-outline': IoSparklesOutline,
  'shield-checkmark-outline': IoShieldCheckmark,
  star: IoStar,
  'grid-outline': IoGridOutline,
  'calendar-outline': IoCalendarOutline,
  'flash-outline': IoFlashOutline,
  'construct-outline': IoConstructOutline,
  'restaurant-outline': IoRestaurantOutline,
  'cash-outline': IoCashOutline,
  cash: IoCashOutline,
  'wallet-outline': IoWalletOutline,
  'ellipse-outline': IoEllipseOutline,
  'shield-checkmark': IoShieldCheckmark,
  calendar: IoCalendarOutline,
  navigate: IoNavigate,
  'location-sharp': IoLocationSharp,
  location: IoLocation,
  'checkmark-circle': IoCheckmarkCircle,
  'information-circle': IoInformationCircle,
  'arrow-forward': IoArrowForward,
  'arrow-forward-circle': IoArrowForwardCircle,
  'chevron-forward': IoChevronForward,
  ribbon: IoRibbonOutline,
  heart: IoHeart,
  'cart-outline': IoCartOutline,
  'person-outline': IoPersonOutline,
  'chevron-back': IoChevronBack,
  'arrow-back': IoArrowBack,
  close: IoClose,
  'close-circle': IoCloseCircle,
  'close-circle-outline': IoCloseCircle,
  'bag-handle-outline': IoBagOutline,
  'bag-outline': IoBagOutline,
  'map-outline': IoMapOutline,
  'card-outline': IoCardOutline,
  'gift-outline': IoGiftOutline,
  'headset-outline': IoHeadsetOutline,
  'megaphone-outline': IoMegaphoneOutline,
  'people-outline': IoPeopleOutline,
  'add-circle-outline': IoAddCircleOutline,
  'remove-circle-outline': IoRemoveCircleOutline,
  'log-out-outline': IoLogOutOutline,
  'create-outline': IoCreateOutline,
  'information-circle-outline': IoInformationCircleOutline,
  'paper-plane-outline': IoPaperPlaneOutline,
  'clipboard-outline': IoClipboardOutline,
  'copy-outline': IoCopyOutline,
  'cube-outline': IoCubeOutline,
  'power-outline': IoPowerOutline,
  'location-outline': IoLocationOutline,
  'trash-outline': IoTrashOutline,
  add: IoAdd,
  'logo-whatsapp': IoLogoWhatsapp,
  checkmark: IoCheckmark,
  'sync-outline': IoSyncOutline,
  'bicycle-outline': IoBicycleOutline,
  'chatbubbles-outline': IoChatbubblesOutline,
  'chatbubble-outline': IoChatbubbleOutline,
  call: IoCall,
  'shield-outline': IoShieldOutline,
  'search-outline': IoSearchOutline,
  'layers-outline': IoLayersOutline,
  'locate-outline': IoLocateOutline,
  'navigate-outline': IoNavigateOutline,
  'star-outline': IoStarOutline,
};

type Props = { ionName: string; size: number; color: string };

export function IonIcon({ ionName, size, color }: Props) {
  const Icon = byIon[ionName] ?? IoEllipseOutline;
  return <Icon size={size} color={color} aria-hidden />;
}
